eureka: #tells about the Eureka server details and its refresh time
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://service-discovery:9007/eureka}

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      routes:
        - id: order-service-id #Order service route declaration
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/** #Path to access the service

        - id: product-service-id #Product service route declaration
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/** #Path to access the service
