eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

      routes:
        - id: order-service-id
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**

        - id: product-service-id
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
