server:
  port: 9005

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      healthcheck:
        enabled: true

spring:
  application:
    name: order-service
  data:
    mongodb:
      database: order-service_db
      port: 27017
