server:
  port: 9004

eureka:
 client:
  serviceUrl:
    defaultZone: ${EUREKA_URI:http://localhost:9007/eureka}
    healthcheck:
      enabled: true

spring:
  application:
    name: product-service
  data:
    mongodb:
      database: product-service_db
      port: 27017
