server:
  port: 9004

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      healthcheck:
        enabled: true


spring:
  application:
    name: product-service
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: product-service_db
      port: 27017
