server:
  port: 8098    #default port where the service will be started

eureka:         #tells about the Eureka server details and its refresh time
  client:
    serviceUrl:
      #defaultZone: ${EUREKA_URI:http://service-discovery:8761/eureka}
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      healthcheck:
        enabled: true


spring:
  application:
    name: product-service   #current service name to be used by the eureka server
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: product-service_db
      port: 27017


